// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ooefpodiqdupfpyqmaif.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9vZWZwb2RpcWR1cGZweXFtYWlmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkzMjA2MTcsImV4cCI6MjA3NDg5NjYxN30.G7xZMi0sJ8_a9u8-4oaFkqVf5NT91wsx3sr0PnQYHas";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});